services:
  # Jugadores Service
  - type: web
    name: jugadores-service
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./jugadores-service/Dockerfile
    dockerContext: .
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: R2DBC_URL
        value: r2dbc:postgresql://basketball_i2b9_user:TNQIEBerIK6MzJfPcPIaohAgyNqlT2dL@dpg-d46banjipnbc73bl8qt0-a.oregon-postgres.render.com:5432/basketball_i2b9?sslMode=require
      - key: DB_USER
        value: basketball_i2b9_user
      - key: DB_PASSWORD
        value: TNQIEBerIK6MzJfPcPIaohAgyNqlT2dL

  # Equipos Service
  - type: web
    name: equipos-service
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./equipos-service/Dockerfile
    dockerContext: .
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: R2DBC_URL
        value: r2dbc:postgresql://basketball_i2b9_user:TNQIEBerIK6MzJfPcPIaohAgyNqlT2dL@dpg-d46banjipnbc73bl8qt0-a.oregon-postgres.render.com:5432/basketball_i2b9?sslMode=require
      - key: DB_USER
        value: basketball_i2b9_user
      - key: DB_PASSWORD
        value: TNQIEBerIK6MzJfPcPIaohAgyNqlT2dL

  # API Gateway
  - type: web
    name: api-gateway
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./api-gateway/Dockerfile
    dockerContext: .
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: JUGADORES_URI
        sync: false
      - key: EQUIPOS_URI
        sync: false

