server:
  port: ${PORT:8082}

spring:
  application:
    name: equipos-service
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/basketballdb}
    username: ${DB_USER:basketuser}
    password: ${DB_PASSWORD:basketpass}
  sql:
    init:
      mode: always
      platform: postgresql

management:
  endpoints:
    web:
      exposure:
        include: health,info
